package com.example.smite.model

import com.example.smite.R
import com.example.smite.data.Dios

object RepositorioDioses {

    /*
    val dioses = listOf(

        //Agni
        Dios(
            nombre = R.string.nombre1,
            avatar = R.drawable.avatar1,
            pasiva = R.drawable.pasiva1,
            apodo = R.string.apodo1,
            rol = R.drawable.hindu,
            lore = R.string.loreAgni,
            roltxt = R.string.hind,
            tipo = R.drawable.mago,
            tipotxt = R.string.mago,
            ataque = R.drawable.ranged,
            ataquetxt = R.string.range,
            dmg = R.drawable.magico,
            dmgtxt = R.string.magico,
            descripcionPasiva = R.string.descripcionPasiva1,
            habilidad1 = R.drawable.habilidad1,
            descripcionHabilidad1 = R.string.descripcionHabilidad1,
            habilidad2 = R.drawable.habilidad2,
            descripcionHabilidad2 = R.string.descripcionHabilidad2,
            habilidad3 = R.drawable.habilidad3,
            descripcionHabilidad3 = R.string.descripcionHabilidad3,
            habilidad4 = R.drawable.habilidad4,
            descripcionHabilidad4 = R.string.descripcionHabilidad4
        ),
        //Anubis
        Dios(
            nombre = R.string.nombre2,
            avatar = R.drawable.avatar2,
            pasiva = R.drawable.pasiva2,
            apodo = R.string.apodo2,
            rol = R.drawable.egipto,
            lore = R.string.loreAnubis,
            roltxt = R.string.egip,
            tipo = R.drawable.mago,
            tipotxt = R.string.mago,
            ataque = R.drawable.ranged,
            ataquetxt = R.string.range,
            dmg = R.drawable.magico,
            dmgtxt = R.string.magico,
            descripcionPasiva = R.string.descripcionPasiva2,
            habilidad1 = R.drawable.habilidad1_2,
            descripcionHabilidad1 = R.string.descripcionHabilidad1_2,
            habilidad2 = R.drawable.habilidad2_2,
            descripcionHabilidad2 = R.string.descripcionHabilidad2_2,
            habilidad3 = R.drawable.habilidad3_2,
            descripcionHabilidad3 = R.string.descripcionHabilidad3_2,
            habilidad4 = R.drawable.habilidad4_2,
            descripcionHabilidad4 = R.string.descripcionHabilidad4_2
        ),
        //Ares
        Dios(
            nombre = R.string.nombre3,
            avatar = R.drawable.avatar3,
            pasiva = R.drawable.pasiva3,
            apodo = R.string.apodo3,
            rol = R.drawable.grecia,
            lore = R.string.loreAres,
            roltxt = R.string.grieg,
            tipo = R.drawable.support,
            tipotxt = R.string.supp,
            ataque = R.drawable.melee,
            ataquetxt = R.string.melee,
            dmg = R.drawable.magico,
            dmgtxt = R.string.magico,
            descripcionPasiva = R.string.descripcionPasiva3,
            habilidad1 = R.drawable.habilidad1_3,
            descripcionHabilidad1 = R.string.descripcionHabilidad1_3,
            habilidad2 = R.drawable.habilidad2_3,
            descripcionHabilidad2 = R.string.descripcionHabilidad2_3,
            habilidad3 = R.drawable.habilidad3_3,
            descripcionHabilidad3 = R.string.descripcionHabilidad3_3,
            habilidad4 = R.drawable.habilidad4_3,
            descripcionHabilidad4 = R.string.descripcionHabilidad4_3
        ),
        //Athena
        Dios(
            nombre = R.string.nombre4,
            avatar = R.drawable.avatar4,
            pasiva = R.drawable.pasiva4,
            apodo = R.string.apodo4,
            rol = R.drawable.grecia,
            lore = R.string.loreAthena,
            roltxt = R.string.grieg,
            tipo = R.drawable.support,
            tipotxt = R.string.supp,
            ataque = R.drawable.melee,
            ataquetxt = R.string.melee,
            dmg = R.drawable.magico,
            dmgtxt = R.string.magico,
            descripcionPasiva = R.string.descripcionPasiva4,
            habilidad1 = R.drawable.habilidad1_4,
            descripcionHabilidad1 = R.string.descripcionHabilidad1_4,
            habilidad2 = R.drawable.habilidad2_4,
            descripcionHabilidad2 = R.string.descripcionHabilidad2_4,
            habilidad3 = R.drawable.habilidad3_4,
            descripcionHabilidad3 = R.string.descripcionHabilidad3_4,
            habilidad4 = R.drawable.habilidad4_4,
            descripcionHabilidad4 = R.string.descripcionHabilidad4_4
        ),
        //Bacchus
        Dios(
            nombre = R.string.nombre5,
            avatar = R.drawable.avatar5,
            pasiva = R.drawable.pasiva5,
            apodo = R.string.apodo5,
            rol = R.drawable.romano,
            lore = R.string.loreBachus,
            roltxt = R.string.roma,
            tipo = R.drawable.support,
            tipotxt = R.string.supp,
            ataque = R.drawable.ranged,
            ataquetxt = R.string.melee,
            dmg = R.drawable.magico,
            dmgtxt = R.string.magico,
            descripcionPasiva = R.string.descripcionPasiva5,
            habilidad1 = R.drawable.habilidad1_5,
            descripcionHabilidad1 = R.string.descripcionHabilidad1_5,
            habilidad2 = R.drawable.habilidad2_5,
            descripcionHabilidad2 = R.string.descripcionHabilidad2_5,
            habilidad3 = R.drawable.habilidad3_5,
            descripcionHabilidad3 = R.string.descripcionHabilidad3_5,
            habilidad4 = R.drawable.habilidad4_5,
            descripcionHabilidad4 = R.string.descripcionHabilidad4_5
        ),
        //Fenrir
        Dios(
            nombre = R.string.nombre6,
            avatar = R.drawable.avatar6,
            pasiva = R.drawable.pasiva6,
            apodo = R.string.apodo6,
            rol = R.drawable.nordico,
            lore = R.string.loreFenrir,
            roltxt = R.string.nord,
            tipo = R.drawable.asesino,
            tipotxt = R.string.asesino,
            ataque = R.drawable.melee,
            ataquetxt = R.string.melee,
            dmg = R.drawable.fisico,
            dmgtxt = R.string.fisic,
            descripcionPasiva = R.string.descripcionPasiva6,
            habilidad1 = R.drawable.habilidad1_6,
            descripcionHabilidad1 = R.string.descripcionHabilidad1_6,
            habilidad2 = R.drawable.habilidad2_6,
            descripcionHabilidad2 = R.string.descripcionHabilidad2_6,
            habilidad3 = R.drawable.habilidad3_6,
            descripcionHabilidad3 = R.string.descripcionHabilidad3_6,
            habilidad4 = R.drawable.habilidad4_6,
            descripcionHabilidad4 = R.string.descripcionHabilidad4_6
        ),
        //Hades
        Dios(
            nombre = R.string.nombre7,
            avatar = R.drawable.avatar7,
            pasiva = R.drawable.pasiva7,
            apodo = R.string.apodo7,
            rol = R.drawable.grecia,
            lore = R.string.loreHades,
            roltxt = R.string.grieg,
            tipo = R.drawable.mago,
            tipotxt = R.string.mago,
            ataque = R.drawable.ranged,
            ataquetxt = R.string.range,
            dmg = R.drawable.magico,
            dmgtxt = R.string.magico,
            descripcionPasiva = R.string.descripcionPasiva7,
            habilidad1 = R.drawable.habilidad1_7,
            descripcionHabilidad1 = R.string.descripcionHabilidad1_7,
            habilidad2 = R.drawable.habilidad2_7,
            descripcionHabilidad2 = R.string.descripcionHabilidad2_7,
            habilidad3 = R.drawable.habilidad3_7,
            descripcionHabilidad3 = R.string.descripcionHabilidad3_7,
            habilidad4 = R.drawable.habilidad4_7,
            descripcionHabilidad4 = R.string.descripcionHabilidad4_7
        ),
        //Poseidon
        Dios(
            nombre = R.string.nombre8,
            avatar = R.drawable.avatar8,
            pasiva = R.drawable.pasiva8,
            apodo = R.string.apodo8,
            rol = R.drawable.grecia,
            lore = R.string.lorePoseidon,
            roltxt = R.string.grieg,
            tipo = R.drawable.mago,
            tipotxt = R.string.mago,
            ataque = R.drawable.ranged,
            ataquetxt = R.string.range,
            dmg = R.drawable.magico,
            dmgtxt = R.string.magico,
            descripcionPasiva = R.string.descripcionPasiva8,
            habilidad1 = R.drawable.habilidad1_8,
            descripcionHabilidad1 = R.string.descripcionHabilidad1_8,
            habilidad2 = R.drawable.habilidad2_8,
            descripcionHabilidad2 = R.string.descripcionHabilidad2_8,
            habilidad3 = R.drawable.habilidad3_8,
            descripcionHabilidad3 = R.string.descripcionHabilidad3_8,
            habilidad4 = R.drawable.habilidad4_8,
            descripcionHabilidad4 = R.string.descripcionHabilidad4_8
        ),
        //Ra
        Dios(
            nombre = R.string.nombre9,
            avatar = R.drawable.avatar9,
            pasiva = R.drawable.pasiva9,
            apodo = R.string.apodo9,
            lore = R.string.loreAgni,
            rol = R.drawable.egipto,
            roltxt = R.string.egip,
            tipo = R.drawable.mago,
            tipotxt = R.string.mago,
            ataque = R.drawable.ranged,
            ataquetxt = R.string.range,
            dmg = R.drawable.magico,
            dmgtxt = R.string.magico,
            descripcionPasiva = R.string.descripcionPasiva9,
            habilidad1 = R.drawable.habilidad1_9,
            descripcionHabilidad1 = R.string.descripcionHabilidad1_9,
            habilidad2 = R.drawable.habilidad2_9,
            descripcionHabilidad2 = R.string.descripcionHabilidad2_9,
            habilidad3 = R.drawable.habilidad3_9,
            descripcionHabilidad3 = R.string.descripcionHabilidad3_9,
            habilidad4 = R.drawable.habilidad4_9,
            descripcionHabilidad4 = R.string.descripcionHabilidad4_9
        ),
        //Skadi
        Dios(
            nombre = R.string.nombre10,
            avatar = R.drawable.avatar10,
            pasiva = R.drawable.pasiva10,
            apodo = R.string.apodo10,
            lore = R.string.loreSkadi,
            rol = R.drawable.nordico,
            roltxt = R.string.nord,
            tipo = R.drawable.cazador,
            tipotxt = R.string.adc,
            ataque = R.drawable.ranged,
            ataquetxt = R.string.range,
            dmg = R.drawable.fisico,
            dmgtxt = R.string.fisic,
            descripcionPasiva = R.string.descripcionPasiva10,
            habilidad1 = R.drawable.habilidad1_10,
            descripcionHabilidad1 = R.string.descripcionHabilidad1_10,
            habilidad2 = R.drawable.habilidad2_10,
            descripcionHabilidad2 = R.string.descripcionHabilidad2_10,
            habilidad3 = R.drawable.habilidad3_10,
            descripcionHabilidad3 = R.string.descripcionHabilidad3_10,
            habilidad4 = R.drawable.habilidad4_10,
            descripcionHabilidad4 = R.string.descripcionHabilidad4_10
        ),

    )
*/
}